# Generated by Django 4.2.2 on 2023-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Processed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("original_file", models.FileField(upload_to="")),
                ("processed_file", models.FileField(upload_to="")),
                ("Transcript", models.TextField()),
                ("Mood", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Satisfaction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("DetailsShared", models.TextField()),
            ],
        ),
    ]
