# Generated by Django 4.2.2 on 2023-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0002_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processed",
            name="DetailsShared",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="processed",
            name="processed_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
