# Generated by Django 4.2.2 on 2023-10-03 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0004_rename_orginal_audio_original_audio_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="original_audio",
        ),
    ]
