# Generated by Django 4.2.2 on 2023-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0006_original_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="original_audio",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
