# Generated by Django 4.2.2 on 2023-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0007_alter_original_audio_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="original_audio",
            name="user",
        ),
    ]
