# Generated by Django 4.2.2 on 2023-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0009_original_audio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="original_audio",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
