# Generated by Django 4.2.2 on 2023-11-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditor_app", "0010_alter_original_audio_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="processed",
            name="code",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
